sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-current-trusty
    packages:
      - chefdk

# Don't `bundle install` which takes about 1.5 mins
install: echo "skip bundle install"

branches:
  only:
  - master

services: docker

env:
  matrix:
  - INSTANCE=connectors-centos-5
  - INSTANCE=mysql56-centos-5
  - INSTANCE=mysql57-centos-5
  - INSTANCE=connectors-centos-6
  - INSTANCE=mysql56-centos-6
  - INSTANCE=mysql57-centos-6
  - INSTANCE=connectors-centos-7
  - INSTANCE=mysql56-centos-7
  - INSTANCE=mysql57-centos-7
  - INSTANCE=connectors-oracle-7
  - INSTANCE=mysql56-oracle-7
  - INSTANCE=mysql57-oracle-7
  - INSTANCE=multi-instance-ubuntu-1604

  fast_finish: true

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/cookstyle
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec -f any -P
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
