---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@5.0.8
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "almalinux-8"
          - "almalinux-9"
          - "almalinux-10"
          - "amazonlinux-2023"
          - "centos-stream-9"
          - "centos-stream-10"
          - "rockylinux-8"
          - "rockylinux-9"
          - "rockylinux-10"
        suite:
          - "resource"
          - "connectors"
          - "mysql55"
          - "mysql56"
          - "mysql57"
        exclude:
          - os: almalinux-8
            suite: mysql55
          - os: almalinux-8
            suite: mysql56
          - os: almalinux-8
            suite: mysql57
          - os: almalinux-9
            suite: mysql55
          - os: almalinux-9
            suite: mysql56
          - os: almalinux-9
            suite: mysql57
          - os: centos-stream-9
            suite: mysql55
          - os: centos-stream-9
            suite: mysql56
          - os: centos-stream-9
            suite: mysql57
          - os: rockylinux-8
            suite: mysql55
          - os: rockylinux-8
            suite: mysql56
          - os: rockylinux-8
            suite: mysql57
          - os: rockylinux-9
            suite: mysql55
          - os: rockylinux-9
            suite: mysql56
          - os: rockylinux-9
            suite: mysql57
          - os: almalinux-10
            suite: mysql55
          - os: almalinux-10
            suite: mysql56
          - os: almalinux-10
            suite: mysql57
          - os: centos-stream-10
            suite: mysql55
          - os: centos-stream-10
            suite: mysql56
          - os: centos-stream-10
            suite: mysql57
          - os: rockylinux-10
            suite: mysql55
          - os: rockylinux-10
            suite: mysql56
          - os: rockylinux-10
            suite: mysql57
          - os: almalinux-10
            suite: resource
          - os: almalinux-10
            suite: connectors
          - os: centos-stream-10
            suite: resource
          - os: centos-stream-10
            suite: connectors
          - os: rockylinux-10
            suite: resource
          - os: rockylinux-10
            suite: connectors
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Install Chef
        uses: actionshub/chef-install@main
      - name: Dokken
        uses: actionshub/test-kitchen@main
        env:
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
      - name: Print debug output on failure
        if: failure()
        run: |
          set -x
          sudo journalctl -l --since today
          KITCHEN_LOCAL_YAML=kitchen.dokken.yml /usr/bin/kitchen exec ${{ matrix.suite }}-${{ matrix.os }} -c "journalctl -l"
